"""create san pham chuan hoa table

Revision ID: 0aaeb677dca4
Revises: c75a5442f123
Create Date: 2026-07-08 15:29:47.941320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaeb677dca4'
down_revision: Union[str, Sequence[str], None] = 'c75a5442f123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('san_pham_chuan_hoa',
    sa.Column('maSPCH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenChuan', sa.String(length=255), nullable=False),
    sa.Column('loai', sa.String(length=100), nullable=True),
    sa.Column('thuongHieu', sa.String(length=100), nullable=True),
    sa.Column('hinhAnhChinh', sa.String(length=500), nullable=True),
    sa.Column('giaThapNhat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('giaCaoNhat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('soSanPhamTho', sa.Integer(), server_default='0', nullable=False),
    sa.Column('soNguonBan', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trangThai', sa.String(length=50), server_default='CHUA_DU_NGUON', nullable=False),
    sa.Column('canKiemTra', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('moTa', sa.Text(), nullable=True),
    sa.Column('ngayTao', sa.DateTime(), nullable=False),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('maSPCH')
    )
    op.create_index(op.f('ix_san_pham_chuan_hoa_maSPCH'), 'san_pham_chuan_hoa', ['maSPCH'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_san_pham_chuan_hoa_maSPCH'), table_name='san_pham_chuan_hoa')
    op.drop_table('san_pham_chuan_hoa')
    # ### end Alembic commands ###
