"""create theo doi gia table

Revision ID: 476eeb86f7bc
Revises: 79f8aef4d56b
Create Date: 2026-07-07 01:20:42.884773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476eeb86f7bc'
down_revision: Union[str, Sequence[str], None] = '79f8aef4d56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theo_doi_gia',
    sa.Column('maTheoDoi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maTaiKhoan', sa.Integer(), nullable=False),
    sa.Column('maSPCH', sa.Integer(), nullable=False),
    sa.Column('giaMongMuon', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('trangThai', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ngayTheoDoi', sa.DateTime(), nullable=False),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maSPCH'], ['san_pham_chuan_hoa.maSPCH'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maTaiKhoan'], ['tai_khoan.maTaiKhoan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maTheoDoi'),
    sa.UniqueConstraint('maTaiKhoan', 'maSPCH', name='uix_theo_doi_gia_user_product')
    )
    op.create_index(op.f('ix_theo_doi_gia_maSPCH'), 'theo_doi_gia', ['maSPCH'], unique=False)
    op.create_index(op.f('ix_theo_doi_gia_maTaiKhoan'), 'theo_doi_gia', ['maTaiKhoan'], unique=False)
    op.create_index(op.f('ix_theo_doi_gia_maTheoDoi'), 'theo_doi_gia', ['maTheoDoi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theo_doi_gia_maTheoDoi'), table_name='theo_doi_gia')
    op.drop_index(op.f('ix_theo_doi_gia_maTaiKhoan'), table_name='theo_doi_gia')
    op.drop_index(op.f('ix_theo_doi_gia_maSPCH'), table_name='theo_doi_gia')
    op.drop_table('theo_doi_gia')
    # ### end Alembic commands ###
