"""create search job tables

Revision ID: 4b5fa4d791ee
Revises: 39c33a31ea3b
Create Date: 2026-07-09 11:56:55.566278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5fa4d791ee'
down_revision: Union[str, Sequence[str], None] = '39c33a31ea3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_job',
    sa.Column('maSearchJob', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('keywordChuanHoa', sa.String(length=255), nullable=True),
    sa.Column('trangThai', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('tongRawItems', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tongFilteredItems', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tongGroups', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errorMessage', sa.String(length=1000), nullable=True),
    sa.Column('ngayTao', sa.DateTime(), nullable=False),
    sa.Column('batDauLuc', sa.DateTime(), nullable=True),
    sa.Column('ketThucLuc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('maSearchJob')
    )
    op.create_index(op.f('ix_search_job_keyword'), 'search_job', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_job_keywordChuanHoa'), 'search_job', ['keywordChuanHoa'], unique=False)
    op.create_index(op.f('ix_search_job_maSearchJob'), 'search_job', ['maSearchJob'], unique=False)
    op.create_index(op.f('ix_search_job_ngayTao'), 'search_job', ['ngayTao'], unique=False)
    op.create_index(op.f('ix_search_job_trangThai'), 'search_job', ['trangThai'], unique=False)
    op.create_table('search_job_source_status',
    sa.Column('maSourceStatus', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maSearchJob', sa.Integer(), nullable=False),
    sa.Column('nguon', sa.String(length=50), nullable=False),
    sa.Column('trangThai', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('rawCount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matchedCount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errorMessage', sa.String(length=1000), nullable=True),
    sa.Column('batDauLuc', sa.DateTime(), nullable=True),
    sa.Column('ketThucLuc', sa.DateTime(), nullable=True),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maSearchJob'], ['search_job.maSearchJob'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maSourceStatus'),
    sa.UniqueConstraint('maSearchJob', 'nguon', name='uix_search_job_source')
    )
    op.create_index(op.f('ix_search_job_source_status_maSearchJob'), 'search_job_source_status', ['maSearchJob'], unique=False)
    op.create_index(op.f('ix_search_job_source_status_maSourceStatus'), 'search_job_source_status', ['maSourceStatus'], unique=False)
    op.create_index(op.f('ix_search_job_source_status_nguon'), 'search_job_source_status', ['nguon'], unique=False)
    op.create_index(op.f('ix_search_job_source_status_trangThai'), 'search_job_source_status', ['trangThai'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_job_source_status_trangThai'), table_name='search_job_source_status')
    op.drop_index(op.f('ix_search_job_source_status_nguon'), table_name='search_job_source_status')
    op.drop_index(op.f('ix_search_job_source_status_maSourceStatus'), table_name='search_job_source_status')
    op.drop_index(op.f('ix_search_job_source_status_maSearchJob'), table_name='search_job_source_status')
    op.drop_table('search_job_source_status')
    op.drop_index(op.f('ix_search_job_trangThai'), table_name='search_job')
    op.drop_index(op.f('ix_search_job_ngayTao'), table_name='search_job')
    op.drop_index(op.f('ix_search_job_maSearchJob'), table_name='search_job')
    op.drop_index(op.f('ix_search_job_keywordChuanHoa'), table_name='search_job')
    op.drop_index(op.f('ix_search_job_keyword'), table_name='search_job')
    op.drop_table('search_job')
    # ### end Alembic commands ###
