"""add foreign key san pham tho to san pham chuan hoa

Revision ID: 59a43d671c27
Revises: 0aaeb677dca4
Create Date: 2026-07-08 15:53:03.368527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a43d671c27'
down_revision: Union[str, Sequence[str], None] = '0aaeb677dca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('UPDATE san_pham_tho SET "maSPCH" = NULL')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_san_pham_tho_maSPCH'), 'san_pham_tho', ['maSPCH'], unique=False)
    op.create_foreign_key(None, 'san_pham_tho', 'san_pham_chuan_hoa', ['maSPCH'], ['maSPCH'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'san_pham_tho', type_='foreignkey')
    op.drop_index(op.f('ix_san_pham_tho_maSPCH'), table_name='san_pham_tho')
    # ### end Alembic commands ###
