"""create email notification log

Revision ID: 59fefcd79832
Revises: 414c9788607d
Create Date: 2026-07-22 03:32:36.746123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fefcd79832'
down_revision: Union[str, Sequence[str], None] = '414c9788607d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_notification_log',
    sa.Column('maNhatKyEmail', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maTheoDoi', sa.Integer(), nullable=True),
    sa.Column('maTaiKhoan', sa.Integer(), nullable=True),
    sa.Column('emailNhan', sa.String(length=255), nullable=False),
    sa.Column('tenNguoiNhan', sa.String(length=255), nullable=True),
    sa.Column('tieuDe', sa.String(length=500), nullable=False),
    sa.Column('loaiThongBao', sa.String(length=50), server_default='price_alert', nullable=False),
    sa.Column('tenSanPham', sa.String(length=1000), nullable=True),
    sa.Column('giaMucTieu', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('giaHienTai', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nguonGia', sa.String(length=255), nullable=True),
    sa.Column('linkSanPham', sa.Text(), nullable=True),
    sa.Column('linkGoc', sa.Text(), nullable=True),
    sa.Column('trangThai', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('soLanThu', sa.Integer(), server_default='0', nullable=False),
    sa.Column('loiGanNhat', sa.Text(), nullable=True),
    sa.Column('ngayTao', sa.DateTime(), nullable=False),
    sa.Column('ngayGui', sa.DateTime(), nullable=True),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maTaiKhoan'], ['tai_khoan.maTaiKhoan'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maTheoDoi'], ['theo_doi_gia.maTheoDoi'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('maNhatKyEmail')
    )
    op.create_index('ix_email_log_theo_doi_trang_thai', 'email_notification_log', ['maTheoDoi', 'trangThai'], unique=False)
    op.create_index('ix_email_log_trang_thai_ngay_tao', 'email_notification_log', ['trangThai', 'ngayTao'], unique=False)
    op.create_index(op.f('ix_email_notification_log_emailNhan'), 'email_notification_log', ['emailNhan'], unique=False)
    op.create_index(op.f('ix_email_notification_log_maNhatKyEmail'), 'email_notification_log', ['maNhatKyEmail'], unique=False)
    op.create_index(op.f('ix_email_notification_log_maTaiKhoan'), 'email_notification_log', ['maTaiKhoan'], unique=False)
    op.create_index(op.f('ix_email_notification_log_maTheoDoi'), 'email_notification_log', ['maTheoDoi'], unique=False)
    op.create_index(op.f('ix_email_notification_log_trangThai'), 'email_notification_log', ['trangThai'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_notification_log_trangThai'), table_name='email_notification_log')
    op.drop_index(op.f('ix_email_notification_log_maTheoDoi'), table_name='email_notification_log')
    op.drop_index(op.f('ix_email_notification_log_maTaiKhoan'), table_name='email_notification_log')
    op.drop_index(op.f('ix_email_notification_log_maNhatKyEmail'), table_name='email_notification_log')
    op.drop_index(op.f('ix_email_notification_log_emailNhan'), table_name='email_notification_log')
    op.drop_index('ix_email_log_trang_thai_ngay_tao', table_name='email_notification_log')
    op.drop_index('ix_email_log_theo_doi_trang_thai', table_name='email_notification_log')
    op.drop_table('email_notification_log')
    # ### end Alembic commands ###
