"""add san_pham_chuan_hoa and lich_su_gia

Revision ID: 76e0f6a1bba6
Revises: c75a5442f123
Create Date: 2026-07-06 08:29:47.804383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e0f6a1bba6'
down_revision: Union[str, Sequence[str], None] = 'c75a5442f123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('san_pham_chuan_hoa',
    sa.Column('maSPCH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenChuanHoa', sa.String(length=255), nullable=False),
    sa.Column('thuongHieu', sa.String(length=50), nullable=True),
    sa.Column('dungLuong', sa.String(length=50), nullable=True),
    sa.Column('modelKey', sa.String(length=100), nullable=True),
    sa.Column('productType', sa.String(length=50), nullable=True),
    sa.Column('anhDaiDien', sa.String(length=500), nullable=True),
    sa.Column('ngayTao', sa.DateTime(), nullable=False),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('maSPCH'),
    sa.UniqueConstraint('productType', 'modelKey', 'dungLuong', name='uix_product_type_model_storage')
    )
    op.create_index(op.f('ix_san_pham_chuan_hoa_maSPCH'), 'san_pham_chuan_hoa', ['maSPCH'], unique=False)
    op.create_table('lich_su_gia',
    sa.Column('maLichSu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maSPTho', sa.Integer(), nullable=False),
    sa.Column('gia', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ngayGhiNhan', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maSPTho'], ['san_pham_tho.maSPTho'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maLichSu')
    )
    op.create_index(op.f('ix_lich_su_gia_maLichSu'), 'lich_su_gia', ['maLichSu'], unique=False)
    op.create_unique_constraint(None, 'san_pham_tho', ['linkGoc'])
    op.create_foreign_key(None, 'san_pham_tho', 'san_pham_chuan_hoa', ['maSPCH'], ['maSPCH'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'san_pham_tho', type_='foreignkey')
    op.drop_constraint(None, 'san_pham_tho', type_='unique')
    op.drop_index(op.f('ix_lich_su_gia_maLichSu'), table_name='lich_su_gia')
    op.drop_table('lich_su_gia')
    op.drop_index(op.f('ix_san_pham_chuan_hoa_maSPCH'), table_name='san_pham_chuan_hoa')
    op.drop_table('san_pham_chuan_hoa')
    # ### end Alembic commands ###
