"""Add tai_khoan table

Revision ID: 79f8aef4d56b
Revises: 76e0f6a1bba6
Create Date: 2026-07-06 21:57:53.794968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f8aef4d56b'
down_revision: Union[str, Sequence[str], None] = '76e0f6a1bba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tai_khoan',
    sa.Column('maTaiKhoan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hoTen', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('matKhauHash', sa.String(length=255), nullable=False),
    sa.Column('vaiTro', sa.String(length=50), nullable=True),
    sa.Column('trangThai', sa.String(length=50), nullable=True),
    sa.Column('ngayTao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ngayCapNhat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('maTaiKhoan')
    )
    op.create_index(op.f('ix_tai_khoan_email'), 'tai_khoan', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tai_khoan_email'), table_name='tai_khoan')
    op.drop_table('tai_khoan')
    # ### end Alembic commands ###
