"""create san pham tho table

Revision ID: c75a5442f123
Revises: 
Create Date: 2026-06-23 19:10:17.397722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c75a5442f123'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('san_pham_tho',
    sa.Column('maSPTho', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maSPCH', sa.Integer(), nullable=True),
    sa.Column('tenSanPham', sa.String(length=255), nullable=False),
    sa.Column('sanTMDT', sa.String(length=50), nullable=False),
    sa.Column('giaHienTai', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('linkGoc', sa.String(length=500), nullable=False),
    sa.Column('hinhAnh', sa.String(length=500), nullable=True),
    sa.Column('danhGia', sa.Float(), nullable=True),
    sa.Column('soLuongDanhGia', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('maSPTho')
    )
    op.create_index(op.f('ix_san_pham_tho_maSPTho'), 'san_pham_tho', ['maSPTho'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_san_pham_tho_maSPTho'), table_name='san_pham_tho')
    op.drop_table('san_pham_tho')
    # ### end Alembic commands ###
